//! Build-time codegen for OpenForge game crates.
//!
//! Each game crate's `build.rs` is a one-liner that calls [`generate`]. This
//! crate reads the crate's `manifest.toml` + `signatures/*.{toml,ron}` +
//! `assets/icon.png` and emits `$OUT_DIR/game_generated.rs`, the file consumed
//! by the game's `src/lib.rs`. It also prints the `cargo:rerun-if-changed=`
//! lines so a touched manifest / signature / asset triggers a rebuild.
//!
//! ## The minimal manifest mirror
//!
//! This crate owns its own minimal `serde` view of `manifest.toml` ([`Manifest`]
//! / [`GameBody`] / [`IconBody`] / [`EngineMirror`]). It deliberately mirrors
//! ONLY the fields the codegen emits as consts — it is **not** the authoritative
//! schema. The real schema lives in `openforge_runtime::manifest::GameManifest`.
//! We keep this build-time mirror separate (rather than depending on
//! `openforge-runtime`) so build-dependencies stay tiny — exactly the rationale
//! the per-game `build.rs` files used to cite, now centralized in ONE place
//! instead of being copied into every game crate.
//!
//! The two views are kept in sync by the `openforge-cli verify-registry` CI
//! gate, which parses every shipped manifest with the REAL runtime schema. If a
//! field the codegen emits drifts from the runtime schema, that gate (or the
//! golden corpus test) fails.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

use serde::Deserialize;

#[derive(Deserialize)]
struct Manifest {
    #[serde(default)]
    engine: EngineMirror,
    game: GameBody,
    #[serde(default)]
    icon: Option<IconBody>,
}

/// Build-time mirror of `[engine]`. We only need `kind` here — the runtime
/// re-parses the full `EngineDecl` from the manifest; the codegen just exposes
/// the declared kind string so `Game::engine_kind()` can return it.
#[derive(Deserialize, Default)]
struct EngineMirror {
    #[serde(default)]
    kind: Option<String>,
}

#[derive(Deserialize)]
struct GameBody {
    id: String,
    display_name: String,
    #[serde(default)]
    tagline: String,
    process_names: Vec<String>,
    #[serde(default)]
    primary_module: Option<String>,
    #[serde(default)]
    supported_versions: Vec<String>,
    #[serde(default)]
    forbidden_services: Vec<String>,
    #[serde(default = "default_true")]
    requires_admin: bool,
    #[serde(default = "default_sort_order")]
    sort_order: i32,
    #[serde(default)]
    dll_file_name: String,
}

#[derive(Deserialize)]
struct IconBody {
    path: String,
}

fn default_true() -> bool {
    true
}
fn default_sort_order() -> i32 {
    1000
}

/// Read this crate's `manifest.toml` + `signatures/` + `assets/`, and emit
/// `$OUT_DIR/game_generated.rs`. Reads `CARGO_MANIFEST_DIR` / `OUT_DIR` from
/// the environment Cargo sets for a build script, so a game `build.rs` is just:
///
/// ```ignore
/// fn main() {
///     openforge_buildgen::generate();
/// }
/// ```
///
/// Panics on a missing/invalid manifest or an unreadable signature (the same
/// hard-failure behavior the inlined `build.rs` files had — a malformed game
/// crate must fail the build loudly, never silently emit a partial module).
pub fn generate() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));

    println!("cargo:rerun-if-changed=manifest.toml");
    println!("cargo:rerun-if-changed=signatures");
    println!("cargo:rerun-if-changed=assets");

    let manifest_path = manifest_dir.join("manifest.toml");
    let manifest_text = fs::read_to_string(&manifest_path).unwrap_or_else(|e| {
        println!(
            "cargo:warning=cannot read {}: {}",
            manifest_path.display(),
            e
        );
        panic!("missing manifest.toml");
    });
    let manifest: Manifest = toml::from_str(&manifest_text).unwrap_or_else(|e| {
        println!("cargo:warning=manifest.toml parse error: {e}");
        panic!("invalid manifest.toml");
    });

    let signatures = enumerate_signatures(&manifest_dir.join("signatures"));
    for (_, abs, _) in &signatures {
        println!("cargo:rerun-if-changed={}", abs.display());
    }

    let icon_path = manifest
        .icon
        .as_ref()
        .map(|i| manifest_dir.join(&i.path))
        .filter(|p| p.exists());

    let mut out = String::new();
    out.push_str("// @generated by build.rs - DO NOT EDIT\n\n");
    out.push_str(&format!(
        "pub const MANIFEST_GAME_ID: &str = {:?};\n",
        manifest.game.id
    ));
    out.push_str(&format!(
        "pub const DISPLAY_NAME: &str = {:?};\n",
        manifest.game.display_name
    ));
    out.push_str(&format!(
        "pub const TAGLINE: &str = {:?};\n",
        manifest.game.tagline
    ));
    out.push_str("pub const PROCESS_NAMES: &[&str] = &[");
    for (i, s) in manifest.game.process_names.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        out.push_str(&format!("{s:?}"));
    }
    out.push_str("];\n");
    out.push_str(&format!(
        "pub const PRIMARY_MODULE: ::core::option::Option<&str> = {};\n",
        match &manifest.game.primary_module {
            Some(s) => format!("::core::option::Option::Some({s:?})"),
            None => "::core::option::Option::None".into(),
        }
    ));
    out.push_str("pub const SUPPORTED_VERSIONS: &[&str] = &[");
    for (i, s) in manifest.game.supported_versions.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        out.push_str(&format!("{s:?}"));
    }
    out.push_str("];\n");
    out.push_str("pub const FORBIDDEN_SERVICES: &[&str] = &[");
    for (i, s) in manifest.game.forbidden_services.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        out.push_str(&format!("{s:?}"));
    }
    out.push_str("];\n");
    out.push_str(&format!(
        "pub const REQUIRES_ADMIN: bool = {};\n",
        manifest.game.requires_admin
    ));
    out.push_str(&format!(
        "pub const SORT_ORDER: i32 = {};\n",
        manifest.game.sort_order
    ));
    out.push_str(&format!(
        "pub const DLL_FILE_NAME: &str = {:?};\n",
        manifest.game.dll_file_name
    ));
    out.push_str(&format!(
        "pub const ENGINE_KIND: ::core::option::Option<&str> = {};\n",
        match &manifest.engine.kind {
            Some(s) => format!("::core::option::Option::Some({s:?})"),
            None => "::core::option::Option::None".into(),
        }
    ));

    match icon_path {
        Some(p) => {
            let lit = p.to_string_lossy().replace('\\', "/");
            out.push_str(&format!(
                "pub const ICON_PNG: &[u8] = include_bytes!({lit:?});\n"
            ));
        }
        None => out.push_str("pub const ICON_PNG: &[u8] = &[];\n"),
    }

    out.push_str("pub const DECLARATIVE_FEATURES: &[::openforge_runtime::DeclFeatureSrc] = &[\n");
    for (name, abs, format) in &signatures {
        let content = fs::read_to_string(abs).unwrap_or_else(|e| {
            println!("cargo:warning=cannot read {}: {}", abs.display(), e);
            panic!("read signature");
        });
        // `format` is the `ConfigFormat` enum token chosen from the file
        // extension by `enumerate_signatures` (`.toml` => Toml, `.ron` => Ron).
        // The runtime re-parses `source` through that format, so the embedded
        // text is verbatim regardless of dialect.
        out.push_str(&format!(
            "    ::openforge_runtime::DeclFeatureSrc {{ name: {name:?}, source: {content:?}, format: {format} }},\n"
        ));
    }
    out.push_str("];\n");

    let dest = out_dir.join("game_generated.rs");
    fs::write(&dest, out).expect("write game_generated.rs");
}

/// Walk `dir` for signature files. Accepts `.toml` and `.ron` (skips anything
/// else); the third tuple element is the fully-qualified `ConfigFormat` enum
/// token to emit verbatim into `game_generated.rs`. Sorted by file stem.
fn enumerate_signatures(dir: &Path) -> Vec<(String, PathBuf, &'static str)> {
    let mut out = Vec::new();
    let Ok(rd) = fs::read_dir(dir) else {
        return out;
    };
    for entry in rd.flatten() {
        let path = entry.path();
        let format = match path.extension().and_then(|s| s.to_str()) {
            Some("toml") => "::openforge_runtime::ConfigFormat::Toml",
            Some("ron") => "::openforge_runtime::ConfigFormat::Ron",
            _ => continue,
        };
        let Some(stem) = path.file_stem().and_then(|s| s.to_str()) else {
            continue;
        };
        out.push((stem.to_string(), path, format));
    }
    out.sort_by(|a, b| a.0.cmp(&b.0));
    out
}
