import type { ComponentType, SVGAttributes } from "react";

import {
  type LucideIcon,
  Activity,
  ArrowUpCircle,
  Bolt,
  Coins,
  Compass,
  Crown,
  Diamond,
  Droplets,
  Eye,
  EyeOff,
  Feather,
  Flame,
  Gauge,
  Gem,
  Ghost,
  Globe2,
  Heart,
  Hexagon,
  Infinity as InfinityIcon,
  Key,
  Layers,
  Lock,
  Magnet,
  Map,
  Moon,
  Mountain,
  Music,
  Package,
  PackagePlus,
  Palette,
  Puzzle,
  Rocket,
  Shield,
  ShieldOff,
  ShieldPlus,
  Shirt,
  Snowflake,
  Sparkles,
  Star,
  Sun,
  Sword,
  Swords,
  Target,
  Timer,
  Trophy,
  Unlock,
  Wallet,
  Wand,
  Wind,
  Wrench,
  Zap,
} from "lucide-react";
import {
  GiBoltShield,
  GiBoots,
  GiBrain,
  GiCardPickup,
  GiCoins as GiCoinsIcon,
  GiCrystalCluster,
  GiFeatheredWing,
  GiFist,
  GiHearts,
  GiJumpAcross,
  GiSonicLightning,
  GiMagicSwirl,
  GiMuscleUp,
  GiNinjaHead,
  GiPunchBlast,
  GiRocketThruster,
  GiRunningShoe,
  GiShieldReflect,
  GiSpeedometer,
  GiSprint,
  GiStarsStack,
  GiSuperMushroom,
  GiSwapBag,
  GiSwordWound,
  GiTrophyCup,
  GiUpgrade,
  GiWalkingBoot,
  GiWingedSword,
} from "react-icons/gi";

export type FeatureIcon = ComponentType<
  SVGAttributes<SVGSVGElement> & { className?: string; strokeWidth?: number }
>;

const ICON_MAP: Record<string, FeatureIcon> = {
  activity: Activity,
  "arrow-up-circle": ArrowUpCircle,
  bolt: Bolt,
  coins: Coins,
  compass: Compass,
  crown: Crown,
  diamond: Diamond,
  droplets: Droplets,
  eye: Eye,
  "eye-off": EyeOff,
  feather: Feather,
  flame: Flame,
  gauge: Gauge,
  gem: Gem,
  ghost: Ghost,
  heart: Heart,
  hexagon: Hexagon,
  infinity: InfinityIcon,
  key: Key,
  layers: Layers,
  lock: Lock,
  magnet: Magnet,
  map: Map,
  moon: Moon,
  mountain: Mountain,
  music: Music,
  package: Package,
  "package-plus": PackagePlus,
  palette: Palette,
  puzzle: Puzzle,
  rocket: Rocket,
  shield: Shield,
  "shield-off": ShieldOff,
  "shield-plus": ShieldPlus,
  shirt: Shirt,
  snowflake: Snowflake,
  sparkles: Sparkles,
  star: Star,
  sun: Sun,
  sword: Sword,
  swords: Swords,
  target: Target,
  timer: Timer,
  trophy: Trophy,
  unlock: Unlock,
  wallet: Wallet,
  wand: Wand,
  wind: Wind,
  wrench: Wrench,
  zap: Zap,

  "gi-bolt-shield": GiBoltShield,
  "gi-boots": GiBoots,
  "gi-brain": GiBrain,
  "gi-card-pickup": GiCardPickup,
  "gi-coins": GiCoinsIcon,
  "gi-crystal-cluster": GiCrystalCluster,
  "gi-feathered-wing": GiFeatheredWing,
  "gi-fist": GiFist,
  "gi-hearts": GiHearts,
  "gi-high-jump": GiJumpAcross,
  "gi-lightning-bolt": GiSonicLightning,
  "gi-magic-swirl": GiMagicSwirl,
  "gi-muscle-up": GiMuscleUp,
  "gi-ninja-head": GiNinjaHead,
  "gi-punch-blast": GiPunchBlast,
  "gi-rocket-thruster": GiRocketThruster,
  "gi-running-shoe": GiRunningShoe,
  "gi-shield-reflect": GiShieldReflect,
  "gi-speedometer": GiSpeedometer,
  "gi-sprint": GiSprint,
  "gi-stars-stack": GiStarsStack,
  "gi-super-mushroom": GiSuperMushroom,
  "gi-swap-bag": GiSwapBag,
  "gi-sword-wound": GiSwordWound,
  "gi-trophy-cup": GiTrophyCup,
  "gi-upgrade": GiUpgrade,
  "gi-walking-boot": GiWalkingBoot,
  "gi-winged-sword": GiWingedSword,
};

const TIER_FALLBACK: Record<string, LucideIcon> = {
  currency: Coins,
  combat: Swords,
  "combat-depth": Sword,
  progression: Trophy,
  movement: Rocket,
  "character movement": Rocket,
  teleportation: Map,
  world: Globe2,
  utility: Wrench,
  general: Hexagon,
};

export function resolveFeatureIcon(
  icon: string | null,
  tier: string,
): FeatureIcon {
  if (icon) {
    const key = icon.toLowerCase().trim();
    const hit = ICON_MAP[key];
    if (hit) return hit;
  }
  return TIER_FALLBACK[tier.toLowerCase()] ?? Hexagon;
}

export function isImageIconPath(icon: string | null): boolean {
  if (!icon) return false;
  return /\.(png|jpe?g|webp|svg|gif)$/i.test(icon) || icon.includes("/");
}
