//! Reads `manifest.toml` + `signatures/*.toml` + `assets/icon.png` from the
//! crate root, generates `$OUT_DIR/game_generated.rs` consumed by `src/lib.rs`.
//!
//! The schema is duplicated here (rather than depending on `openforge-runtime`)
//! to keep build-time dependencies tiny.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

use serde::Deserialize;

#[derive(Deserialize)]
struct Manifest {
    game: GameBody,
    #[serde(default)]
    icon: Option<IconBody>,
}

#[derive(Deserialize)]
struct GameBody {
    id: String,
    display_name: String,
    #[serde(default)]
    tagline: String,
    process_names: Vec<String>,
    #[serde(default)]
    primary_module: Option<String>,
    #[serde(default)]
    supported_versions: Vec<String>,
    #[serde(default)]
    forbidden_services: Vec<String>,
    #[serde(default = "default_true")]
    requires_admin: bool,
    #[serde(default = "default_sort_order")]
    sort_order: i32,
    #[serde(default)]
    dll_file_name: String,
}

#[derive(Deserialize)]
struct IconBody {
    path: String,
}

fn default_true() -> bool {
    true
}
fn default_sort_order() -> i32 {
    1000
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));

    println!("cargo:rerun-if-changed=manifest.toml");
    println!("cargo:rerun-if-changed=signatures");
    println!("cargo:rerun-if-changed=assets");

    let manifest_path = manifest_dir.join("manifest.toml");
    let manifest_text = fs::read_to_string(&manifest_path).unwrap_or_else(|e| {
        println!(
            "cargo:warning=cannot read {}: {}",
            manifest_path.display(),
            e
        );
        panic!("missing manifest.toml");
    });
    let manifest: Manifest = toml::from_str(&manifest_text).unwrap_or_else(|e| {
        println!("cargo:warning=manifest.toml parse error: {e}");
        panic!("invalid manifest.toml");
    });

    let signatures = enumerate_signatures(&manifest_dir.join("signatures"));
    for (_, abs) in &signatures {
        println!("cargo:rerun-if-changed={}", abs.display());
    }

    let icon_path = manifest
        .icon
        .as_ref()
        .map(|i| manifest_dir.join(&i.path))
        .filter(|p| p.exists());

    let mut out = String::new();
    out.push_str("// @generated by build.rs - DO NOT EDIT\n\n");
    out.push_str(&format!(
        "pub const MANIFEST_GAME_ID: &str = {:?};\n",
        manifest.game.id
    ));
    out.push_str(&format!(
        "pub const DISPLAY_NAME: &str = {:?};\n",
        manifest.game.display_name
    ));
    out.push_str(&format!(
        "pub const TAGLINE: &str = {:?};\n",
        manifest.game.tagline
    ));
    out.push_str("pub const PROCESS_NAMES: &[&str] = &[");
    for (i, s) in manifest.game.process_names.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        out.push_str(&format!("{s:?}"));
    }
    out.push_str("];\n");
    out.push_str(&format!(
        "pub const PRIMARY_MODULE: ::core::option::Option<&str> = {};\n",
        match &manifest.game.primary_module {
            Some(s) => format!("::core::option::Option::Some({s:?})"),
            None => "::core::option::Option::None".into(),
        }
    ));
    out.push_str("pub const SUPPORTED_VERSIONS: &[&str] = &[");
    for (i, s) in manifest.game.supported_versions.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        out.push_str(&format!("{s:?}"));
    }
    out.push_str("];\n");
    out.push_str("pub const FORBIDDEN_SERVICES: &[&str] = &[");
    for (i, s) in manifest.game.forbidden_services.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        out.push_str(&format!("{s:?}"));
    }
    out.push_str("];\n");
    out.push_str(&format!(
        "pub const REQUIRES_ADMIN: bool = {};\n",
        manifest.game.requires_admin
    ));
    out.push_str(&format!(
        "pub const SORT_ORDER: i32 = {};\n",
        manifest.game.sort_order
    ));
    out.push_str(&format!(
        "pub const DLL_FILE_NAME: &str = {:?};\n",
        manifest.game.dll_file_name
    ));

    match icon_path {
        Some(p) => {
            let lit = p.to_string_lossy().replace('\\', "/");
            out.push_str(&format!(
                "pub const ICON_PNG: &[u8] = include_bytes!({lit:?});\n"
            ));
        }
        None => out.push_str("pub const ICON_PNG: &[u8] = &[];\n"),
    }

    out.push_str("pub const DECLARATIVE_FEATURES: &[::openforge_runtime::DeclFeatureSrc] = &[\n");
    for (name, abs) in &signatures {
        let content = fs::read_to_string(abs).unwrap_or_else(|e| {
            println!("cargo:warning=cannot read {}: {}", abs.display(), e);
            panic!("read signature");
        });
        // Format is currently always Toml because `enumerate_signatures`
        // only accepts `.toml` files. RON is added in a later refactor phase.
        out.push_str(&format!(
            "    ::openforge_runtime::DeclFeatureSrc {{ name: {name:?}, source: {content:?}, format: ::openforge_runtime::ConfigFormat::Toml }},\n"
        ));
    }
    out.push_str("];\n");

    let dest = out_dir.join("game_generated.rs");
    fs::write(&dest, out).expect("write game_generated.rs");
}

fn enumerate_signatures(dir: &Path) -> Vec<(String, PathBuf)> {
    let mut out = Vec::new();
    let Ok(rd) = fs::read_dir(dir) else {
        return out;
    };
    for entry in rd.flatten() {
        let path = entry.path();
        if path.extension().and_then(|s| s.to_str()) != Some("toml") {
            continue;
        }
        let Some(stem) = path.file_stem().and_then(|s| s.to_str()) else {
            continue;
        };
        out.push((stem.to_string(), path));
    }
    out.sort_by(|a, b| a.0.cmp(&b.0));
    out
}
