[package]
name        = "openforge-game-glacier-007"
description = "OpenForge game module: 007 First Light (Glacier 2 engine)"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
authors.workspace      = true
repository.workspace   = true
build       = "build.rs"

[dependencies]
openforge-core    = { workspace = true }
openforge-runtime = { workspace = true }

[build-dependencies]
openforge-buildgen = { workspace = true }
