//! Template game crate.
//!
//! `openforge-cli new-game` copies this directory to `crates/games/<id>/` and
//! substitutes the `__TEMPLATE_*__` placeholders. Do not edit this file by hand
//! except to update the canonical scaffolding shape.

include!(concat!(env!("OUT_DIR"), "/game_generated.rs"));

pub const GAME_ID: &str = "_template";

pub struct TemplateGame;

impl openforge_runtime::Game for TemplateGame {
    fn id(&self) -> &'static str {
        GAME_ID
    }
    fn display_name(&self) -> &'static str {
        DISPLAY_NAME
    }
    fn tagline(&self) -> &'static str {
        TAGLINE
    }
    fn process_names(&self) -> &'static [&'static str] {
        PROCESS_NAMES
    }
    fn primary_module(&self) -> Option<&'static str> {
        PRIMARY_MODULE
    }
    fn supported_versions(&self) -> &'static [&'static str] {
        SUPPORTED_VERSIONS
    }
    fn forbidden_services(&self) -> &'static [&'static str] {
        FORBIDDEN_SERVICES
    }
    fn icon_png(&self) -> &'static [u8] {
        ICON_PNG
    }
    fn requires_admin(&self) -> bool {
        REQUIRES_ADMIN
    }
    fn sort_order(&self) -> i32 {
        SORT_ORDER
    }
    fn declarative_features(&self) -> &'static [openforge_runtime::DeclFeatureSrc] {
        DECLARATIVE_FEATURES
    }
}

// NOTE: The template is intentionally NOT registered with `register_game!`.
// It compiles so that the scaffolder can copy + substitute, but does not
// pollute the shipped registry. New game crates (created from this template)
// add the `openforge_runtime::register_game!(YourGame);` call themselves.
